services:

  app:
    build: .
    volumes:
      - ./:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: geheim    
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: '["Referer", "Origin"]'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always          
    environment: 
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: geheim
      POSTGRES_DB: app_db
    volumes:                 
      - pg-data:/var/lib/postgresql/data

volumes:
  pgadmin-data:
  pg-data: